name: Bazel

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Mount Bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Bazel test all targets
        run: bazel test //...

      - name: Bazel build all targets
        run: bazel build //...
